apiVersion: v1
kind: Namespace
metadata:
  name: pnp-opsera-jai-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pnp-opsera-jai-deployment
  namespace: pnp-opsera-jai-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:494c051b0ae34c1ce5fa24e1732aebb56f5b7138

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pnp-opsera-jai-label
  name: pnp-opsera-jai-service
  namespace: pnp-opsera-jai-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---